language: csharp
mono: none

notifications:
  email: false

branches:
  only:
    - master

matrix:
  include:
    - os: linux 
      dist: xenial # Ubuntu 16.04
      dotnet: 2.1.502
    - os: linux
      dist: xenial # Ubuntu 16.04
      dotnet: 2.1.502
      env: TargetFrameworkOverride=netstandard2.0
    - os: osx
      dotnet: 2.1.507
      osx_image: xcode8.3 # dotnet requires at least this version

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -qq update; EXTRA_CONSTANT=-p:BuildConstants=NOCONSENSUSLIB; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then ulimit -S -n 4096; EXTRA_CONSTANT=-p:BuildConstants=NOCONSENSUSLIB; fi

script:
  - dotnet build ./Bitcoin3.Tests/Bitcoin3.Tests.csproj /p:TargetFrameworkOverride=$TargetFrameworkOverride -c Release -f netcoreapp2.1  $EXTRA_CONSTANT
  - dotnet test --no-build -v n -c Release -f netcoreapp2.1 ./Bitcoin3.Tests/Bitcoin3.Tests.csproj --filter "RestClient=RestClient|RPCClient=RPCClient|Protocol=Protocol|Core=Core|UnitTest=UnitTest" -p:ParallelizeTestCollections=false
